vich_uploader:
    db_driver: orm

    mappings:
        accident_image:
            uri_prefix: /images/accident
            upload_destination: '%kernel.project_dir%/public/images/accident'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update : true
